spring:
    r2dbc:
        url: r2dbc:pool:mysql://localhost:3306/reactive
        username: root
        password: root

    sql:
        init:
            mode: never
            schema-locations: classpath:db/schema.sql

logging:
    level:
        org:
            springframework:
                r2dbc: DEBUG