spring:
    datasource:
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/batchtest?serverTimezone=UTC&characterEncoding=UTF-8
            username: root
            password: root
            maximum-pool-size: 5
            minimum-idle: 5
            connection-timeout: 5000
    sql:
        init:
            mode: always
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    batch:
        job:
            names: ${job.name:NONE}
            enabled: false
        jdbc:
            initialize-schema: always

logging:
    level:
        org:
            springframework:
                jdbc:
                    core:
                        JdbcTemplate: debug
