# 유레카 서버가 웹서비스의 성격으로 구동된다.
# 포트 번호 지정
server:
  port: 8761

# 마이크로서비스를 담당하는 스프링부트 프레임 워크에
# 각각의 마이크로서비스에 고유한 아이디를 부여하는 설명
spring:
  application:
    name: discoveryservice


## client 설정 ##
# 현재 유레카 서버를 구동하는데 왜 client 설정이 필요한가?
# eureka 라이브러리가 포함된 채 스프링부트가 구동이 되면
# 기본적으로 eureka 클라이언트의 역할로서 어딘가에 등록하는 작업을 시도한다.
# 아래 설정들은 기본값이 true로 현재 프로젝트를 client의 역할로 전화번호부에 등록하는 것과 같다.
# 현재 프로젝트는 서버(전화번호부)가 될 것인데 자신의 정보를 자신에게 등록하는 현상이 된다.
# 의미가 없는 작업이므로 false로 세팅해준다.
# 정리하자면 현재 프로젝트는 유레카 서버(전화번호부)이므로 클라이언트 역할로 자동으로 등록되는 세팅을 막아주는 설정이다.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false