spring:
  h2:
    console:
      enabled: true
  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 6379
    host: 127.0.0.1

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  cache:
    jcache:
      config: classpath:ehcache.xml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
