spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          self-oauth:
            authorization-grant-type: client_credentials
#            설정 않하면 client_secret_basic
#            client-authentication-method: client_secret_basic
            client-id: album-resource-server
            client-secret: album-resource-server-secret
            scope:
              - friend.read
              - friend.write
            provider: self-oauth

        provider:
          self-oauth:
            issuer-uri: http://localhost:9000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8081
  shutdown: graceful

