spring:
  security:
    oauth2:
      client:
        registration:
          self-oauth:
            authorization-grant-type: authorization_code
            client-id: oauth2client
            client-secret: oauth2client-secret
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/self-oauth
            scope:
              - friend.read
              - friend.write
              - album.read
              - album.write
              - openid
            provider: self-oauth

        provider:
          self-oauth:
            issuer-uri: http://localhost:9000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080
  shutdown: graceful

logging:
  root: debug