spring:
  datasource:
    url: jdbc:mysql://master.chjqzcooytli.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8
    slave-list:
      - name: slave_1
        url: jdbc:mysql://slave-1.chjqzcooytli.ap-northeast-2.rds.amazonaws.com/test?useSSL=false&useUnicode=true&characterEncoding=utf8
      - name: slave_2
        url: jdbc:mysql://slave-2.chjqzcooytli.ap-northeast-2.rds.amazonaws.com/test?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:


  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        show-sql: true
        generate-ddl: true

# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#